/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.engsoft.main;

import br.com.engsoft.controll.ControleDeFila;
import br.com.engsoft.utils.AlteraImagens;
import br.com.engsoft.utils.utilitarios;
import java.awt.Color;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import br.com.engsoft.controll.SenhasControl;
import br.com.engsoft.controll.ControleDeTelas;
import javax.swing.UIManager;

/**
 *
 * @author Raul
 */
public class GuicheDefault extends javax.swing.JFrame {

    ControleDeFila controleFila = new ControleDeFila();

    boolean pausado = false;
    String senhaAtualB = null;
    String senhaAnteriorB = null;

    String senhaAtualC = null;
    String senhaAnteriorC = null;

    String senhaAtualD = null;
    String senhaAnteriorD = null;

    /**
     * Creates new form AtendenteView
     */
    public GuicheDefault() {
        initComponents();

        configuracaoTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblSenhaAnterior = new javax.swing.JLabel();
        txtSenhaAnterior = new javax.swing.JTextField();
        lblSenhaAtual = new javax.swing.JLabel();
        txtSenhaAtual = new javax.swing.JTextField();

        btnProximo = new javax.swing.JButton();
        btnProximo.setToolTipText("Próxima Senha da Fila");
        lblAtendente = new javax.swing.JLabel();
        lblNomeAtendente = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblData.setText(dataAtual());
        lblTitulo = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        btnFinalizar.setToolTipText("Finalizar Atendimento");  
        tbtnPausarContinuar = new javax.swing.JToggleButton();
        tbtnPausarContinuar.setToolTipText("Pausar/Continuar Atendimento");
        btnTransferir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        lblSenhaAnterior.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSenhaAnterior.setText("Anterior");

        txtSenhaAnterior.setEditable(false);
        txtSenhaAnterior.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtSenhaAnterior.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSenhaAnterior.setEnabled(false);
        txtSenhaAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaAnteriorActionPerformed(evt);
            }
        });

        lblSenhaAtual.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSenhaAtual.setText("Atual");

        txtSenhaAtual.setEditable(false);
        txtSenhaAtual.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txtSenhaAtual.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSenhaAtual.setEnabled(false);
        txtSenhaAtual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSenhaAtualActionPerformed(evt);
            }
        });

        btnProximo.setText("Chamar Próximo");
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        lblAtendente.setText("Atendente:");

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTitulo.setText("ATENDENTE B");

        btnFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/engsoft/img/Fim.png"))); // NOI18N
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        tbtnPausarContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/engsoft/img/pause.png"))); // NOI18N
        tbtnPausarContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnPausarContinuarActionPerformed(evt);
            }
        });

        btnTransferir.setText("Transferir");
        btnTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferirActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(btnProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addComponent(btnTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(42, 42, 42)
                                                .addComponent(lblSenhaAnterior)))
                                        .addGap(18, 18, 18))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSenhaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tbtnPausarContinuar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSenhaAtual, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(lblSenhaAtual))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTitulo)
                                .addGap(27, 27, 27)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnVoltar))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAtendente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNomeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblData, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSenhaAnterior)
                    .addComponent(lblSenhaAtual))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenhaAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnProximo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tbtnPausarContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTransferir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNomeAtendente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblData, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSenhaAtualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaAtualActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaAtualActionPerformed

    private void txtSenhaAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaAnteriorActionPerformed

    private void tbtnPausarContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnPausarContinuarActionPerformed
        if (tbtnPausarContinuar.isSelected() == false) {
            tbtnPausarContinuar.setIcon(new AlteraImagens().pauseIcon());

        } else if (tbtnPausarContinuar.isSelected() == true) {
            tbtnPausarContinuar.setIcon(new AlteraImagens().continueIcon());
        }

    }//GEN-LAST:event_tbtnPausarContinuarActionPerformed

    private void btnTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTransferirActionPerformed

        Object[] options = {"Sim", "Não"};
        if (txtSenhaAtual.getText().equals(null) || txtSenhaAtual.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você não está em atendimento no momento");
        } else {
            int i = JOptionPane.showOptionDialog(null,
                    "Deseja realmente transmitir o cliente\npara o próximo atendente?", "Saída",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                    options, options[0]);
            if (i == JOptionPane.YES_OPTION) {
                senhaAnteriorB = senhaAtualB;
                txtSenhaAnterior.setText(senhaAnteriorB);//não vai poder ser definido como B, usar IF
                txtSenhaAtual.setText("");
                controleFila.tranfereGuicheC(senhaAnteriorB, new utilitarios().dataAtual("dd/MM/yyyy"));
            }
        }


    }//GEN-LAST:event_btnTransferirActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        try {
            //senhasControl sc = chamarProximoCliente(lblTitulo.getText().charAt(10), new utilitarios().dataAtual("dd/MM/yyyy"));
            SenhasControl sc = new ControleDeFila().chamarProximoCliente('B', new utilitarios().dataAtual("dd/MM/yyyy"));
            if (sc != null || !sc.equals("")) {
                senhaAtualB = sc.getSenha();
                txtSenhaAtual.setText(senhaAtualB);
            } else {
                JOptionPane.showMessageDialog(null, "Não há senha a ser chamada.");
            }

        } catch (SQLException ex) {
            Logger.getLogger(GuicheDefault.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed

        Object[] options = {"Sim", "Não"};
        if (txtSenhaAtual.getText().equals(null) || txtSenhaAtual.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Você não está em atendimento no momento");
        } else {
            int i = JOptionPane.showOptionDialog(null,
                    "Deseja realmente transmitir o cliente\npara o próximo atendente?", "Saída",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null,
                    options, options[0]);
            if (i == JOptionPane.YES_OPTION) {
                controleFila.finalizaAtendimento(txtSenhaAtual.getText(), new utilitarios().dataAtual("dd/MM/yyyy"));
                senhaAnteriorB = senhaAtualB;
                txtSenhaAnterior.setText(senhaAnteriorB);//não vai poder ser definido como B, usar IF
                txtSenhaAtual.setText("");
            }
        }


    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed

         new ControleDeTelas().abrirSelecionaOperacao(this, TelaLogin.usuarioM);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                break;

            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GuicheDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GuicheDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GuicheDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GuicheDefault.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GuicheDefault().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnProximo;
    public javax.swing.JButton btnTransferir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel lblAtendente;
    private javax.swing.JLabel lblData;
    public javax.swing.JLabel lblNomeAtendente;
    private javax.swing.JLabel lblSenhaAnterior;
    private javax.swing.JLabel lblSenhaAtual;
    public javax.swing.JLabel lblTitulo;
    public javax.swing.JToggleButton tbtnPausarContinuar;
    private javax.swing.JTextField txtSenhaAnterior;
    private javax.swing.JTextField txtSenhaAtual;
    // End of variables declaration//GEN-END:variables

    public String dataAtual() {
        DateFormat df = new SimpleDateFormat("dd/MM/yyyy");
        Date today = Calendar.getInstance().getTime();
        String reportDate = df.format(today);

        return reportDate;
    }

    private void configuracaoTela() {
        //Bloqueia o redimensionamento
        this.getContentPane().setBackground(new Color(211, 211, 211));
        this.setResizable(false);
        //Coloca o jframe no centro
        this.setLocationRelativeTo(null);
        //Fechar toda a Aplicação ao clicar no botão Fechar
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

}
