/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.engsoft.main;

import javax.swing.JFrame;
import br.com.engsoft.controll.ControleDeTelas;

/**
 *
 * @author Raul
 */
public class SelecionaOperacao extends javax.swing.JFrame {

    ControleDeTelas controleTela = new ControleDeTelas();

    public SelecionaOperacao() {
        initComponents();
        configuracaoTela();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lblTitulo = new javax.swing.JLabel();
        rbtnAdministrador = new javax.swing.JRadioButton();
        rbtnGuicheA = new javax.swing.JRadioButton();
        rbtnGuicheB = new javax.swing.JRadioButton();
        rbtnGuicheC = new javax.swing.JRadioButton();
        rbtnGuicheD = new javax.swing.JRadioButton();
        btnAbrir = new javax.swing.JButton();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblTitulo.setText("Selecione o módulo que deseja abrir:");

        buttonGroup1.add(rbtnAdministrador);
        rbtnAdministrador.setText("Administrador");
        rbtnAdministrador.setEnabled(false);

        buttonGroup1.add(rbtnGuicheA);
        rbtnGuicheA.setText("Guichê A");
        rbtnGuicheA.setEnabled(false);

        buttonGroup1.add(rbtnGuicheB);
        rbtnGuicheB.setText("Guichê B");
        rbtnGuicheB.setEnabled(false);

        buttonGroup1.add(rbtnGuicheC);
        rbtnGuicheC.setText("Guichê C");
        rbtnGuicheC.setEnabled(false);
        rbtnGuicheC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnGuicheCActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtnGuicheD);
        rbtnGuicheD.setText("Guichê D");
        rbtnGuicheD.setEnabled(false);

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 15, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(btnAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnVoltar)
                .addGap(36, 36, 36))
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbtnGuicheA)
                    .addComponent(rbtnGuicheC)
                    .addComponent(rbtnGuicheD)
                    .addComponent(rbtnAdministrador)
                    .addComponent(rbtnGuicheB))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(rbtnAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnGuicheA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnGuicheB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnGuicheC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnGuicheD)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAbrir)
                    .addComponent(btnVoltar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnGuicheCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnGuicheCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnGuicheCActionPerformed

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        if (rbtnAdministrador.isSelected()) {
            controleTela.abrirTelaAdm(this);
        } else if (rbtnGuicheA.isSelected()) {
            controleTela.abrirGuicheA(this, TelaLogin.atendente);
        } else if (rbtnGuicheB.isSelected()) {
            controleTela.abrirGuicheDefault(this, "ATENDENTE B", TelaLogin.atendente);
        } else if (rbtnGuicheC.isSelected()) {
            controleTela.abrirGuicheDefault(this, "ATENDENTE C", TelaLogin.atendente);
        } else if (rbtnGuicheD.isSelected()) {
            controleTela.abrirGuicheDefault(this, "ATENDENTE D", TelaLogin.atendente);
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        controleTela.abrirLogin(this);
    }//GEN-LAST:event_btnVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelecionaOperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelecionaOperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelecionaOperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelecionaOperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SelecionaOperacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel lblTitulo;
    protected javax.swing.JRadioButton rbtnAdministrador;
    protected javax.swing.JRadioButton rbtnGuicheA;
    protected javax.swing.JRadioButton rbtnGuicheB;
    protected javax.swing.JRadioButton rbtnGuicheC;
    protected javax.swing.JRadioButton rbtnGuicheD;
    // End of variables declaration//GEN-END:variables

    private void configuracaoTela() {
        //Bloqueia o redimensionamento
        this.setResizable(false);
        //Coloca o jframe no centro
        this.setLocationRelativeTo(null);
        //Fechar toda a Aplicação ao clicar no botão Fechar
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

}
