/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.engsoft.main.refactor;

import br.com.engsoft.main.refactor.TelaLogin;
import br.com.engsoft.controll.ControleDeFila;
import br.com.engsoft.controll.ControleDeTelas;
import br.com.engsoft.utils.AlteraImagens;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author Raul
 */
public class TelaGuicheA extends javax.swing.JFrame {

    ControleDeFila controleFila = new ControleDeFila();
    ControleDeTelas controleTela = new ControleDeTelas();

    /**
     * Creates new form GuicheA
     */
    public TelaGuicheA() {
        initComponents();
        configuracaoTela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gbtnGerar = new javax.swing.ButtonGroup();
        btnVoltar = new javax.swing.JButton();
        lblNomeAtendente = new javax.swing.JLabel();
        lblAtendente = new javax.swing.JLabel();
        btnGerarSenha = new javax.swing.JButton();
        tbtnPausarContinuar = new javax.swing.JToggleButton();
        tbtnPausarContinuar.setToolTipText("Pausar/Continuar Atendimento");
        lblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        pnlTipoSenha = new javax.swing.JPanel();
        rbtnSenhaPreferencial = new javax.swing.JRadioButton();
        rbtnSenhaNormal = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(0, 0));

        btnVoltar.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        lblNomeAtendente.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N

        lblAtendente.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        lblAtendente.setText("Atendente:");

        btnGerarSenha.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        btnGerarSenha.setText("Gerar Senha");
        btnGerarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarSenhaActionPerformed(evt);
            }
        });

        tbtnPausarContinuar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/engsoft/img/pause.png"))); // NOI18N
        tbtnPausarContinuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbtnPausarContinuarActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Lato", 1, 24)); // NOI18N
        lblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitulo.setText("ATENDENTE A");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/engsoft/img/logo64.png"))); // NOI18N

        gbtnGerar.add(rbtnSenhaPreferencial);
        rbtnSenhaPreferencial.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        rbtnSenhaPreferencial.setText("Preferencial");
        rbtnSenhaPreferencial.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtnSenhaPreferencial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSenhaPreferencialActionPerformed(evt);
            }
        });
        pnlTipoSenha.add(rbtnSenhaPreferencial);

        gbtnGerar.add(rbtnSenhaNormal);
        rbtnSenhaNormal.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        rbtnSenhaNormal.setText("Normal");
        rbtnSenhaNormal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rbtnSenhaNormal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnSenhaNormalActionPerformed(evt);
            }
        });
        pnlTipoSenha.add(rbtnSenhaNormal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblAtendente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblNomeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lblTitulo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnGerarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(tbtnPausarContinuar, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE))))
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlTipoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTipoSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnGerarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tbtnPausarContinuar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNomeAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAtendente))
                .addGap(1, 1, 1))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        
        controleTela.abrirSelecionaOperacao(this, TelaLogin.usuarioM);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void rbtnSenhaPreferencialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSenhaPreferencialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSenhaPreferencialActionPerformed

    private void tbtnPausarContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbtnPausarContinuarActionPerformed

        if (tbtnPausarContinuar.isSelected() == false) {

            tbtnPausarContinuar.setIcon(new AlteraImagens().pauseIcon());

        } else if (tbtnPausarContinuar.isSelected() == true) {
            tbtnPausarContinuar.setIcon(new AlteraImagens().continueIcon());

        }
    }//GEN-LAST:event_tbtnPausarContinuarActionPerformed

    private void btnGerarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarSenhaActionPerformed

        if (tbtnPausarContinuar.isSelected() == false) {
            if (rbtnSenhaNormal.isSelected()) {
                JOptionPane.showMessageDialog(null, "Senha gerada: " + controleFila.gerarSenhaNormal());

            } else if (rbtnSenhaPreferencial.isSelected()) {
                JOptionPane.showMessageDialog(null, "Senha gerada: " + controleFila.gerarSenhaPreferencial());
            } else {
                JOptionPane.showMessageDialog(null, "Selecione o tipo de senha!");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Você não pode gerar senhas, pois está em momento de pausa.");
        }

    }//GEN-LAST:event_btnGerarSenhaActionPerformed

    private void rbtnSenhaNormalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnSenhaNormalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnSenhaNormalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {

                javax.swing.UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                break;

            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaGuicheA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaGuicheA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaGuicheA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaGuicheA.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaGuicheA().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGerarSenha;
    private javax.swing.JButton btnVoltar;
    private javax.swing.ButtonGroup gbtnGerar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAtendente;
    public javax.swing.JLabel lblNomeAtendente;
    public javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlTipoSenha;
    private javax.swing.JRadioButton rbtnSenhaNormal;
    private javax.swing.JRadioButton rbtnSenhaPreferencial;
    private javax.swing.JToggleButton tbtnPausarContinuar;
    // End of variables declaration//GEN-END:variables

    private void configuracaoTela() {
        pnlTipoSenha.setBackground(new Color(211, 211, 211));
        rbtnSenhaNormal.setBackground(new Color(211, 211, 211));
        rbtnSenhaPreferencial.setBackground(new Color(211, 211, 211));
        
        this.getContentPane().setBackground(new Color(211, 211, 211));
        //Bloqueia o redimensionamento
        this.setResizable(false);
        //Coloca o jframe no centro
        this.setLocationRelativeTo(null);
        //Fechar toda a Aplicação ao clicar no botão Fechar
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        tbtnPausarContinuar.requestFocus();
    }

}
